municipales_homepage:
    path:     /
    defaults: { _controller: MunicipalesBundle:Default:index }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

municipales_candidacy_step_conditions:
    path:     /condiciones-alta-candidatura
    defaults: { _controller: MunicipalesBundle:Candidacy:stepConditions }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step1:
    path:     /alta-candidatura
    defaults: { _controller: MunicipalesBundle:Candidacy:step1 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
 
municipales_candidacy_step_verify:
    path:     /alta-candidatura-verificacion
    defaults: { _controller: MunicipalesBundle:Candidacy:stepVerify }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step2:
    path:     /alta-candidatura-paso-2
    defaults: { _controller: MunicipalesBundle:Candidacy:step2 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step3:
    path:     /alta-candidatura-paso-3
    defaults: { _controller: MunicipalesBundle:Candidacy:step3 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step4:
    path:     /alta-candidatura-paso-4
    defaults: { _controller: MunicipalesBundle:Candidacy:step4 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step5:
    path:     /alta-candidatura-paso-5
    defaults: { _controller: MunicipalesBundle:Candidacy:step5 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step6:
    path:     /alta-candidatura-paso-6
    defaults: { _controller: MunicipalesBundle:Candidacy:step6 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
municipales_candidacy_step7:
    path:     /alta-candidatura-paso-7
    defaults: { _controller: MunicipalesBundle:Candidacy:step7 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

municipales_candidacy_step8:
    path:     /alta-candidatura-paso-8
    defaults: { _controller: MunicipalesBundle:Candidacy:step8 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl 

# Extra for accept/reject candidates
municipales_candidacy_accept:
    path:     /candidate/accept/{id}
    defaults: { _controller: MunicipalesBundle:Candidacy:accept }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl  

municipales_candidacy_reject:
    path:     /candidate/reject/{id}
    defaults: { _controller: MunicipalesBundle:Candidacy:reject }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl  
        
# http://municipales2015.listabierta.org/elmunicipioregistrado/resultados
town_results:
    path:     /{address}/resultados
    defaults: { _controller: MunicipalesBundle:Town:results }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
                                      
town_candidacy_vote_step1:
    path:     /{address}/vota
    defaults: { _controller: MunicipalesBundle:Town:vote1 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
 
town_candidacy_step_verify:
    path:     /{address}/vota-verificacion
    defaults: { _controller: MunicipalesBundle:Town:voteVerify }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

town_candidacy_vote_step2:
    path:     /{address}/vota-paso-2
    defaults: { _controller: MunicipalesBundle:Town:vote2 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

town_candidacy_vote_step3:
    path:     /{address}/vota-paso-3
    defaults: { _controller: MunicipalesBundle:Town:vote3 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

town_candidacy_vote_step4:
    path:     /{address}/vota-paso-4
    defaults: { _controller: MunicipalesBundle:Town:vote4 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

town_candidacy_vote_step5:
    path:     /{address}/vota-paso-5
    defaults: { _controller: MunicipalesBundle:Town:vote5 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

town_candidacy_vote_step6:
    path:     /{address}/vota-paso-6
    defaults: { _controller: MunicipalesBundle:Town:vote6 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

town_candidacy_vote_step7:
    path:     /{address}/vota-paso-7
    defaults: { _controller: MunicipalesBundle:Town:vote7 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

town_candidacy_vote_step8:
    path:     /{address}/vota-paso-8
    defaults: { _controller: MunicipalesBundle:Town:vote8 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
        
# Candidate                                               
candidate_step1:
    path:     /{address}/altacandidaturas
    defaults: { _controller: MunicipalesBundle:Candidate:step1 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl

candidate_step_verify:
    path:     /{address}/alta-candidaturas-verificacion
    defaults: { _controller: MunicipalesBundle:Candidate:stepVerify }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl
 
candidate_step2:
    path:     /{address}/alta-candidaturas-paso-2
    defaults: { _controller: MunicipalesBundle:Candidate:step2 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl          

candidate_step3:
    path:     /{address}/alta-candidaturas-paso-3
    defaults: { _controller: MunicipalesBundle:Candidate:step3 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl 
         
candidate_step4:
    path:     /{address}/alta-candidaturas-paso-4
    defaults: { _controller: MunicipalesBundle:Candidate:step4 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl  

candidate_step5:
    path:     /{address}/alta-candidaturas-paso-5
    defaults: { _controller: MunicipalesBundle:Candidate:step5 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl  

candidate_step6:
    path:     /{address}/alta-candidaturas-paso-6
    defaults: { _controller: MunicipalesBundle:Candidate:step6 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl  
        
candidate_step7:
    path:     /{address}/alta-candidaturas-paso-7
    defaults: { _controller: MunicipalesBundle:Candidate:step7 }
    requirements:
        _locale: es_es|es_eu|es_gl|es_gl  

# Manager

manager_index:
    path:     /manager
    defaults: { _controller: MunicipalesBundle:Manager:index }
    
manager_verify_phone:
    path:     /manager/verify-phone/{phone}
    defaults: { _controller: MunicipalesBundle:Manager:verifyPhone }

manager_purge_phones:
    path:     /manager/purge-phones
    defaults: { _controller: MunicipalesBundle:Manager:purgePhones }
    
manager_purge_candidacies:
    path:     /manager/purge-candidacies
    defaults: { _controller: MunicipalesBundle:Manager:purgeCandidacies }

manager_purge_voters:
    path:     /manager/purge-voters
    defaults: { _controller: MunicipalesBundle:Manager:purgeVoters }
    
manager_purge_candidates:
    path:     /manager/purge-candidates
    defaults: { _controller: MunicipalesBundle:Manager:purgeCandidates }

   
# http://municipales2015.listabierta.org./sms/inbound   
municipales_sms_inbound_callback:
    path:     /sms/inbound
    defaults: { _controller: MunicipalesBundle:SMSInbound:index }
    
# http://municipales2015.listabierta.org./sms/callback   
municipales_sms_callback:
    path:     /sms/callback
    defaults: { _controller: MunicipalesBundle:SMSInbound:callback }
    
login:
    pattern:   /login
    defaults:  { _controller: MunicipalesBundle:Security:login }
login_check:
    pattern:   /login_check
    
admin_logout:
    pattern:   /logout
